config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  get "static_pages/home"
  get "/help" => 'static_pages#help'
  get "/about" => 'static_pages#about'
  get "/contact" => 'static_pages#contact'

  root 'static_pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, presence: true, length: { maximum: 50 }
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	validates :password, length: { minimum: 6 }
	validates :password_confirmation, length: { minimum: 6 }
	has_secure_password

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.hash(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

private
	def create_remember_token
		#create remember_token
		self.remember_token = User.hash(User.new_remember_token)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		render 'new'
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)

		if user && user.authenticate(params[:session][:password])
			# Sign in the user and redirect to profile page
			sign_in user
			redirect_to user
		else
			# Redisplay page with error message
			flash.now[:danger] = 'Invalid email / password combination.'
			render 'new'
		end
	end

	def destroy
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end
  
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)

  	if @user.save
      sign_in @user
  		flash[:success] = "Welcome to the Sample App"
      redirect_to @user
  	else
  		render 'new'
  	end
  end


  private
  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	#returns full title on a per-page basis
	def full_title(page_title)
		base_title = "Ruby on Rails Tutorial Sample App"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.hash(remember_token))
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		current_user.update_attribute(:remember_token, User.hash(User.new_remember_token))
		cookies.delete[:remember_token]
		self.current_user = nil
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.hash(cookies[:remember_token])
		current_user ||= User.find_by(remember_token: remember_token)
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar media-object")
	end
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
				<span class="sr-only">Toggle Navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "Rails Sample App", root_path, class: 'navbar-brand' %>
		</div>
		<div class="collapse navbar-collapse" id="navbar-collapse">
			<ul class="nav navbar-nav">
				<li><%= link_to "Home", root_path %></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">About <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><%= link_to "About Us", about_path %></li>
						<li><%= link_to "Contact Us", contact_path %></li>
						<li><%= link_to "Help", help_path %></li>
					</ul>
				</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<% if signed_in? %>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><%= link_to "Profile", current_user %></li>
							<li><%= link_to "Settings", '#' %></li>
							<li class="divider"></li>
							<li><%= link_to "Sign Out", signout_path, method: 'delete' %></li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to "Sign In", signin_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/nav' %>
	<div class="container">
		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
		<%= yield %>
	</div>
	<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error-explanation">
	<div class="alert alert-error">The form contains <%= pluralize(@user.errors.count, "error") %></div>
	<ul>
	<% @user.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
	</ul>
</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>Lorem ipsum dolar sit amet.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<h1>Contact Us</h1>
<p>You can contact us in all the usual ways:</p>
<ul>
	<li><a href="mailto:malevolence@gmail.com">Email</a></li>
	<li><a href="http://twitter.com/malevolenc">Twitter</a></li>
	<li><a href="http://malevlence.org">Website</a></li>
</ul>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>To get help with this tutorail, visit <a href="http://railstutorial.org/" target="_blank">railstutorial.org</a></p>
<p>To view the associated book, visit <a href="http://railstutorial.org/book" target="_blank">railstutorial.org/book</a></p>

app/views/static_pages/home.html.erb
<div class="jumbotron">
<h1>Ruby on Rails Tutorial Sample App</h1>
<p class="text-center">This is the homepage for the ruby on rails tutorial sample application (a twitter clone).</p>
<p class="text-center"><%= link_to "Sign Up Now!", signup_path, class: "btn btn-primary btn-lg" %></p>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign Up</h1>
<%= form_for(@user) do |f| %>
<%= render('shared/error_messages') %>
<div class="form-group">
	<%= f.label :name %>
	<%= f.text_field :name, class: "form-control" %>
</div>
<div class="form-group">
	<%= f.label :email %>
	<%= f.text_field :email, class: "form-control" %>
</div>
<div class="form-group">
	<%= f.label :password %>
	<%= f.password_field :password, class: "form-control" %>
</div>
<div class="form-group">
	<%= f.label :password_confirmation, "Confirmation" %>
	<%= f.password_field :password_confirmation, class: "form-control" %>
</div>
<div class="form-group">
	<%= f.submit "Create my Account", class: "btn btn-primary btn-lg" %>
</div>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="media">
	<div class="pull-left"><%= gravatar_for @user %></div>
	<div class="media-body">
		<h1 class="media-heading"><%= @user.name %></h1>
		<p><%= @user.email %></p>
	</div>
</div>